import { Injectable, BadRequestException, ConflictException, NotFoundException, InternalServerErrorException, Inject, UnauthorizedException } from '@nestjs/common';
import { NodePgDatabase } from 'drizzle-orm/node-postgres';
import { DATABASE_CONNECTION } from '../database/database-connection.token';
import * as schema from '../auth/schema';
import { subject, member } from '../auth/schema';
import { eq, and, asc } from 'drizzle-orm';
import { CreateSubjectDto, UpdateSubjectDto } from './dto/subject.dto';

@Injectable()
export class SubjectsService {

  // Inject the database connection
  constructor(
    @Inject(DATABASE_CONNECTION)
    private readonly db: NodePgDatabase<typeof schema>,
  ) { }

  // Get all subjects for the authenticated user's school.
  async getSubjects(userId: string) {
    const subjects = await this.db
      .select({
        id: subject.id,
        name: subject.name,
        department: subject.department,
        createdAt: subject.createdAt,
        updatedAt: subject.updatedAt,
      })   // select these 
      .from(member)   // Join on the member's table and 
      .innerJoin(subject, eq(subject.organizationId, member.organizationId))  // subjects record where the subject's organisation id matches the user's organisation id
      .where(eq(member.userId, userId))      // Use the userId to get the user's member record
      .orderBy(asc(subject.createdAt));

      console.log("subjects from database", subjects);

    return { success: 'Subjects fetched successfully', data: subjects };
  }

  // Create a new subject linked to the authenticated user's school.
  async createSubject(userId: string, data: CreateSubjectDto) {
    // DTO + global ValidationPipe handles validation and transformation (trim, IsIn, etc.)

    let newSubject: typeof subject.$inferSelect | undefined;

    try {
      // Run inside a transaction so the user lookup and insert are atomic.
      // Closes the TOCTOU window without incurring extra latency.
      await this.db.transaction(async (tx) => {

        // Verify user has a school set up
        const [currentMember] = await tx
          .select({ organizationId: member.organizationId })
          .from(member)
          .where(eq(member.userId, userId))
          .limit(1); // stop scanning after first hit
        if (!currentMember) {
          throw new UnauthorizedException('Unauthorised operation');
        }
        if (!currentMember.organizationId) {
          throw new BadRequestException('Please set up your school information first');
        }

        // Insert the new subject — subjectName is already trimmed by the DTO transform.
        [newSubject] = await tx
          .insert(subject)
          .values({
            // id is auto generated by the database
            name: data.name,
            department: data.department ?? null,
            organizationId: currentMember.organizationId,
          }).returning();
      });

      return { success: 'Subject created successfully', data: newSubject };
    } catch (error) {
      this.rethrowOrWrap(error, 'Failed to create subject');
    }
  }

  // Update an existing subject that belongs to the authenticated user's school.
  async updateSubject(userId: string, subjectId: string, data: UpdateSubjectDto) {
    // DTO + global ValidationPipe handles validation and transformation (trim, IsIn, etc.)

    // Verify the user exists and has a school
    const [currentMember] = await this.db
      .select({ organizationId: member.organizationId }) // *** fetch only the column we need
      .from(member)
      .where(eq(member.userId, userId))
      .limit(1); // *** stop scanning after first hit
    if (!currentMember) {
      throw new UnauthorizedException('Unauthorised operation');
    }
    if (!currentMember.organizationId) {
      throw new NotFoundException('School not found. Please create a school first.');
    }

    // Build the update payload — only include fields explicitly provided in the request.
    // (undefined = not sent → leave DB value unchanged).
    // (null = field cleared to "" -> set to null in db)
    const subjectUpdateData: Partial<typeof subject.$inferInsert> = {};

    // subject name is always sent in the payload
    subjectUpdateData.name = data.name

    // department is optional
    if (data.department !== undefined) {
      subjectUpdateData.department = data.department ?? null;
    }

    // Single UPDATE — no extra round trip needed.
    // The WHERE clause checks both subject.id and subject.organizationId, so ownership is
    // enforced implicitly: a subject from another school will simply not match.
    try {
      const [updated] = await this.db
        .update(subject)
        .set(subjectUpdateData)
        .where(and(eq(subject.id, subjectId), eq(subject.organizationId, currentMember.organizationId)))  // ensure the subject ids match and the subject belongs to the user's school
        .returning();

      // No row updated → subject doesn't exist or doesn't belong to this school
      if (!updated) {
        throw new NotFoundException('Subject not found');
      }

      return { success: 'Subject updated successfully', data: updated };
    } catch (error) {
      this.rethrowOrWrap(error, 'Failed to update subject');
    }
  }

  // Error handler — re-throws known NestJS exceptions; wraps unexpected ones.
  private rethrowOrWrap(error: unknown, fallbackMessage: string): never {
    if (
      error instanceof BadRequestException ||
      error instanceof UnauthorizedException ||
      error instanceof ConflictException ||
      error instanceof NotFoundException ||
      error instanceof InternalServerErrorException
    ) {
      throw error;
    }

    // Postgres unique constraint violation: unique("subject_organizationId_name_key")
    if (error instanceof Error && (error.message.includes('unique') || error.message.includes('duplicate'))) {
      throw new ConflictException('A subject with this name already exists in your school');
    }

    throw new InternalServerErrorException(fallbackMessage);
  }
}