// Generated by AI for review later.

/**
 * Types extracted from Drizzle ORM queries
 * 
 * There are several ways to get types from Drizzle:
 * 
 * 1. Extract from service method return type (EASIEST - what you're already doing!)
 *    Use: Awaited<ReturnType<typeof serviceMethod>>
 * 
 * 2. Use InferSelectModel for base table types (for simple queries)
 *    Use: InferSelectModel<typeof table>
 * 
 * 3. Manually construct types for relational queries (most control)
 */

import type { InferSelectModel } from 'drizzle-orm';
import { 
  user,
  school, 
  academicTerm, 
  subject, 
  assessmentStructure, 
  gradingEntry, 
  student,
  studentSubject,
  assessment,
  assessmentScore,
  classTable
} from '../auth/schema';

// ============================================================================
// Option 1: Extract base table types using InferSelectModel
// ============================================================================
// This gives you the type of a single row from each table
export type User = InferSelectModel<typeof user>;
export type School = InferSelectModel<typeof school>;
export type AcademicTerm = InferSelectModel<typeof academicTerm>;
export type Subject = InferSelectModel<typeof subject>;
export type AssessmentStructure = InferSelectModel<typeof assessmentStructure>;
export type GradingEntry = InferSelectModel<typeof gradingEntry>;
export type Student = InferSelectModel<typeof student>;
export type StudentSubject = InferSelectModel<typeof studentSubject>;
export type Assessment = InferSelectModel<typeof assessment>;
export type AssessmentScore = InferSelectModel<typeof assessmentScore>;
export type Class = InferSelectModel<typeof classTable>;

// ============================================================================
// Option 2: Manually construct the relational query type
// ============================================================================
// This matches the exact structure of your getUserWithRelations query
// Use this when you need full type safety for nested relations
export type UserWithRelations = User & {
  school: School | null;
  academicTerm: (AcademicTerm & {
    class: Class | null;
    subjects: Subject[];
    assessmentStructure: AssessmentStructure[];
    gradingEntry: GradingEntry[];
    students: (Student & {
      subjects: (StudentSubject & {
        subject: Subject | null;
        assessments: (Assessment & {
          scores: AssessmentScore[];
        })[];
      })[];
    })[];
  }) | null;
};

// ============================================================================
// Option 3: Extract from service method (RECOMMENDED)
// ============================================================================
// Import the service and extract the type:
// import { UsersService } from './users.service';
// export type UserWithRelationsFromService = Awaited<ReturnType<UsersService['getUserWithRelations']>>;
// 
// However, this requires the service to be instantiable, so it's better to do this
// in a separate file or use the manual type above.
