// Generated by AI for review later.

/**
 * Types extracted from Drizzle ORM queries
 * 
 * There are several ways to get types from Drizzle:
 * 
 * 1. Extract from service method return type (EASIEST - what you're already doing!)
 *    Use: Awaited<ReturnType<typeof serviceMethod>>
 * 
 * 2. Use InferSelectModel for base table types (for simple queries)
 *    Use: InferSelectModel<typeof table>
 * 
 * 3. Manually construct types for relational queries (most control)
 */

import type { InferSelectModel } from 'drizzle-orm';
import { 
  user,
  organization, 
  academicTerm, 
  subject, 
  assessmentStructure, 
  gradingEntry, 
  student,
  studentSubjectEnrollment,
  subjectClassAssignment,
  assessment,
  assessmentScore,
} from '../auth/schema';

// ============================================================================
// Option 1: Extract base table types using InferSelectModel
// ============================================================================
// This gives you the type of a single row from each table
export type User = InferSelectModel<typeof user>;
export type Organization = InferSelectModel<typeof organization>;
export type AcademicTerm = InferSelectModel<typeof academicTerm>;
export type Subject = InferSelectModel<typeof subject>;
export type AssessmentStructure = InferSelectModel<typeof assessmentStructure>;
export type GradingEntry = InferSelectModel<typeof gradingEntry>;
export type Student = InferSelectModel<typeof student>;
export type StudentSubjectEnrollment = InferSelectModel<typeof studentSubjectEnrollment>;
export type SubjectClassAssignment = InferSelectModel<typeof subjectClassAssignment>;
export type Assessment = InferSelectModel<typeof assessment>;
export type AssessmentScore = InferSelectModel<typeof assessmentScore>;

// ============================================================================
// Option 2: Manually construct the relational query type
// ============================================================================
// This matches the shape of the admin-facing queries.
// Use this when you need full type safety for nested relations.
export type UserWithRelations = User & {
  organization: Organization | null;
  academicTerm: (AcademicTerm & {
    subjectClassAssignments: SubjectClassAssignment[];
    assessmentStructures: AssessmentStructure[];
    gradingEntries: GradingEntry[];
    students: (Student & {
      enrollments: (StudentSubjectEnrollment & {
        assessments: (Assessment & {
          scores: AssessmentScore[];
        })[];
      })[];
    })[];
  }) | null;
};

// ============================================================================
// Option 3: Extract from service method (RECOMMENDED)
// ============================================================================
// Import the service and extract the type:
// import { UsersService } from './users.service';
// export type UserWithRelationsFromService = Awaited<ReturnType<UsersService['getUserWithRelations']>>;
// 
// However, this requires the service to be instantiable, so it's better to do this
// in a separate file or use the manual type above.
