import { Injectable, BadRequestException, ConflictException, NotFoundException, InternalServerErrorException } from '@nestjs/common';
import { Inject, UnauthorizedException } from '@nestjs/common';
import { NodePgDatabase } from 'drizzle-orm/node-postgres';
import { DATABASE_CONNECTION } from '../database/database-connection.token';
import { academicTerm, member } from '../auth/schema';
import { eq, and, desc, ne } from 'drizzle-orm';
import { CreateTermDto, UpdateTermDto } from './dto/term.dto';
import { validateTermDates } from './term-validation';
import * as schema from '../auth/schema';

@Injectable()
export class TermService {
  // Inject the database connection
  constructor(
    @Inject(DATABASE_CONNECTION)
    private readonly db: NodePgDatabase<typeof schema>,
  ) { }

  // Get all academic terms for the authenticated user's organisation
  async getTerms(userId: string) {
    const terms = await this.db
      .select({
        id: academicTerm.id,
        academicYear: academicTerm.academicYear,
        term: academicTerm.term,
        termDays: academicTerm.termDays,
        termStart: academicTerm.termStart,
        termEnd: academicTerm.termEnd,
        status: academicTerm.status,
        organizationId: academicTerm.organizationId,
        createdAt: academicTerm.createdAt,
        updatedAt: academicTerm.updatedAt,
      })
      .from(member)
      .innerJoin(academicTerm, eq(academicTerm.organizationId, member.organizationId))
      .where(eq(member.userId, userId))
      .orderBy(desc(academicTerm.createdAt));

    return {
      success: 'Terms fetched successfully',
      data: terms,
    };
  }

  // Create a new academic term
  async createTerm(userId: string, termData: CreateTermDto) {
    // Cross-field date validation (DTO handles basic type/presence/enum checks)
    const dateCheck = validateTermDates(termData.termStart, termData.termEnd);
    if (!dateCheck.isValid) {
      throw new BadRequestException(dateCheck.error);
    }

    try {
      // Run inside a transaction so the user-check + insert are atomic for TOCTOU-safe pattern
      await this.db.transaction(async (tx) => {

        // Verify user exists and is the organisation's owner (TODO: change to admin later)
        const [currentMember] = await tx
          .select({ organizationId: member.organizationId })
          .from(member)
          .where(and(eq(member.userId, userId), eq(member.role, 'owner')))
          .limit(1);

        // If the user does not exist, throw an unauthorised exception or is not the organisation's admin
        if (!currentMember) {
          throw new UnauthorizedException('Unauthorised operation');
        }

        // Insert the term (id is auto-generated by the database)
        // The DB unique constraint (organizationId, academicYear, term) enforces no duplicates;
        // violations are caught in rethrowOrWrap.
        await tx
          .insert(academicTerm)
          .values({
            academicYear: termData.academicYear,
            term: termData.term,
            termDays: termData.termDays ?? null,
            termStart: termData.termStart ? new Date(termData.termStart) : null,
            termEnd: termData.termEnd ? new Date(termData.termEnd) : null,
            organizationId: currentMember.organizationId,
          });
      });

      return { success: 'Term created successfully', data: null };
    } catch (error) {
      this.rethrowOrWrap(error, 'Failed to create term. Please check your inputs and try again.');
    }
  }

  // Update an existing academic term (dates and days only)
  // academicYear and term enum are immutable — they define the term's identity
  async updateTerm(userId: string, termId: string, termData: UpdateTermDto) {
    // Cross-field date validation
    const dateCheck = validateTermDates(termData.termStart, termData.termEnd);
    if (!dateCheck.isValid) {
      throw new BadRequestException(dateCheck.error);
    }

    // Verify user + get organizationId outside the transaction (single UPDATE is atomic)
    const [currentMember] = await this.db
      .select({ organizationId: member.organizationId })
      .from(member)
      .where(eq(member.userId, userId))
      .limit(1);
    // If the user does not exist, throw an unauthorised exception
    if (!currentMember) {
      throw new UnauthorizedException('Unauthorised operation');
    }

    // Build update payload — only include fields explicitly provided.
    const updateData: Partial<typeof academicTerm.$inferInsert> = {};
    updateData.id = termId;
    if (termData.termDays !== undefined) updateData.termDays = termData.termDays ?? null;
    if (termData.termStart !== undefined) updateData.termStart = termData.termStart ? new Date(termData.termStart) : null;
    if (termData.termEnd !== undefined) updateData.termEnd = termData.termEnd ? new Date(termData.termEnd) : null;
    if (termData.status !== undefined) updateData.status = termData.status;
    if (Object.keys(updateData).length === 0) {
      throw new BadRequestException('No fields to update');
    }

    try {
      await this.db.transaction(async (tx) => {
        // Only one ACTIVE term per organisation (partial unique index). Demote others before activating this row.
        if (termData.status === 'ACTIVE') {
          await tx
            .update(academicTerm)
            .set({ status: 'DRAFT' })
            .where(
              and(
                eq(academicTerm.organizationId, currentMember.organizationId),
                eq(academicTerm.status, 'ACTIVE'),
                ne(academicTerm.id, termId),
              ),
            );
        }

        // Now, update the term
        const [updated] = await tx
          .update(academicTerm)
          .set(updateData)
          .where(
            and(
              eq(academicTerm.id, termId),
              eq(academicTerm.organizationId, currentMember.organizationId),
            ),
          )
          .returning({ id: academicTerm.id });

        // If the term is not found, throw a not found exception
        if (!updated) {
          throw new NotFoundException('Term not found for this school. Update failed.');
        }
      });

      return { success: 'Term updated successfully', data: null };
    } catch (error) {
      this.rethrowOrWrap(error, 'Failed to update term');
    }
  }

  // Error handler — mirrors school.service rethrowOrWrap
  private rethrowOrWrap(error: unknown, fallbackMessage: string): never {
    if (
      error instanceof BadRequestException ||
      error instanceof UnauthorizedException ||
      error instanceof ConflictException ||
      error instanceof NotFoundException ||
      error instanceof InternalServerErrorException
    ) {
      throw error;
    }

    // DB unique constraint: (organizationId, academicYear, term)
    if (error instanceof Error && (error.message.includes('unique') || error.message.includes('duplicate'))) {
      throw new ConflictException('A term with this academic year and term slot already exists');
    }

    throw new InternalServerErrorException(fallbackMessage);
  }
}